apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: developer-project-test
    app.kubernetes.io/part-of: app-developer-project-test
  name: developer-project-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: developer-project-test
      app.kubernetes.io/part-of: app-developer-project-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: developer-project-test
        app.kubernetes.io/part-of: app-developer-project-test
    spec:
      containers:
      - image: europe-west2-docker.pkg.dev/quick-yen-359707/poc/developer-project-test:latest
        imagePullPolicy: Always
        name: developer-project-test
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
      serviceAccountName: default
status: {}