apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: developer-project-test
    app.kubernetes.io/part-of: developer-project-test
  name: developer-project-test
spec:
  ports:
  - name: 80-tcp
    protocol: TCP
    port: 80
    targetPort: 80
  - name: 3000-tcp
    protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app.kubernetes.io/name: developer-project-test
    app.kubernetes.io/part-of: app-developer-project-test
status:
  loadBalancer: {}